### ISSUE TITLE
Provide conda package for Python 3.4

### ISSUE THREAD

**Issue by FlorianWilhelm** [conda-forge/turbodbc-feedstock#15]
Since Python 3.4 is still quite common as default, especially with Cloudera distributions and given the fact that not always an environment with a version > 3.4 can be created, it would be nice if also a conda package for Python 3.4 could be provided. Thanks!

**Comment by xhochy** [comment]
I'm sorry but I think you're out of luck for this. `conda-forge` has dropped support for 3.4 some time ago and it would be a massive effort to setup the whole chain simply for `turbodbc`.
